
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_new_rails_app_development
  username: postgres
  password: 1234
  port: 5433
  host: localhost

test:
  <<: *default
  database: my_new_rails_app_test
  username: postgres
  password: 1234
  port: 5433

production:
  <<: *default
  database: my_new_rails_app_production
  username: my_new_rails_app
  password: <%= ENV["MY_NEW_RAILS_APP_DATABASE_PASSWORD"] %>
